version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile.${APP_ENV:-prod}
    container_name: symfony-api
    volumes:
      - .:/var/www
      - ./var/profiler:/tmp/xdebug-profiler
    environment:
      APP_ENV: ${APP_ENV:-dev}
      APP_DEBUG: ${APP_DEBUG:-1}
      XDEBUG_MODE: debug,profile
      XDEBUG_CONFIG: "client_host=host.docker.internal client_port=9004 discover_client_host=0"
    networks:
      - app-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  webserver:
    image: nginx:alpine
    container_name: symfony-nginx
    ports:
      - "8080:80"
    volumes:
      - ./public:/var/www/public
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge