version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: symfony-api
    volumes:
      - .:/var/www
    environment:
      APP_ENV: ${APP_ENV-dev}
      APP_DEBUG: ${APP_DEBUG-1}  # Включаем дебаг по умолчанию
      XDEBUG_MODE: ${XDEBUG_MODE-debug}
      XDEBUG_CONFIG: "client_host=host.docker.internal"
    networks:
      - app-network
    extra_hosts:
      - "host.docker.internal:host-gateway"  # Для работы Xdebug

  webserver:
    image: nginx:alpine
    container_name: symfony-nginx
    ports:
      - "8080:80"
    volumes:
      - ./public:/var/www/public
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge